[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_spl_token_demo = "FPcitBxjEg9ujAUQ4AgiaMahBVHTYJK3suvoCGKzR5ra"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/hp/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
